site_name: Todo List API
site_description: API moderne de gestion de tâches avec FastAPI et Streamlit
site_author: Todo List Team
site_url: https://your-username.github.io/todo-list-best-practices

repo_name: your-username/todo-list-best-practices
repo_url: https://github.com/your-username/todo-list-best-practices

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - macros

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation: usage.md
  - API Reference: api.md
  - Architecture: architecture.md
  - Tests: tests.md
  - Déploiement: deployment.md
  - Contribution: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/todo-list-best-practices
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/todo-list-best-practices
