name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install hatch
        run: pip install hatch

      - name: Install dependencies
        run: hatch env create && hatch run pip install -e .[dev]

      - name: Run Ruff (linter)
        run: hatch run ruff check src tests

      - name: Run Black (formatter check)
        run: hatch run black --check src tests

      - name: Run tests
        run: hatch run pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: docker build -t todo-list-best-practices .

  deploy:
    runs-on: ubuntu-latest
    needs: lint-test-build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Render Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
